import { JobSpec, Quote, Mission, VoiceTrustSignal } from "./types";

export const mockJobSpec: JobSpec = {
  id: "job-001",
  caseType: "broken_key_inside_lock",
  urgency: "locked_out_now",
  propertyType: "apartment",
  doorType: "main_entry",
  lockType: "deadbolt",
  doorOpen: false,
  keyStolen: false,
  brokenKeyVisible: true,
  needRekey: false,
  newKeysNeeded: 0,
  idealPrice: 100,
  maxPrice: 150,
  budgetFlexibility: "strict",
  approvalRequiredAboveBudget: true,
  authorizationConfirmed: true,
  locationCity: "San Francisco",
  locationZip: "94109",
  createdAt: new Date().toISOString(),
};

export const mockVoiceTrustSignals: Record<string, VoiceTrustSignal[]> = {
  vendorA: [
    {
      id: "vt-a-1",
      quoteId: "quote-a",
      questionType: "hidden_fees",
      vendorText: "Uh... well, it depends on the lock.",
      pauseMs: 1800,
      fillerWords: ["Uh", "well"],
      evasivePhrases: ["it depends"],
      confidenceScore: 35,
      trustLevel: "Low",
      signals: ["Long pause (1.8s)", "Evasive language", "Filler words"],
      recommendedPush: "Force a firm cap on labor before dispatch.",
    },
  ],
  vendorB: [
    {
      id: "vt-b-1",
      quoteId: "quote-b",
      questionType: "price",
      vendorText: "It's $130 total, including dispatch.",
      pauseMs: 200,
      fillerWords: [],
      evasivePhrases: [],
      confidenceScore: 95,
      trustLevel: "High",
      signals: ["Quick response", "Direct language"],
      recommendedPush: "Confirm no-drill policy.",
    },
  ],
  vendorC: [
    {
      id: "vt-c-1",
      quoteId: "quote-c",
      questionType: "hidden_fees",
      vendorText: "Um, we can drop it to $145 if you book right now.",
      pauseMs: 1200,
      fillerWords: ["Um"],
      evasivePhrases: [],
      confidenceScore: 65,
      trustLevel: "Medium",
      signals: ["Moderate pause", "Negotiation detected"],
      recommendedPush: "Lock in the $145 all-in rate immediately.",
    },
  ],
};

export const mockQuotes: Quote[] = [
  {
    id: "quote-a",
    missionId: "mission-001",
    vendorName: "Speedy Lock & Key",
    phone: "(555) 019-2834",
    etaMinutes: 20,
    dispatchFee: 39,
    laborFee: null,
    partsFee: null,
    afterHoursFee: null,
    taxesAndOther: null,
    totalEstimate: null,
    isTotalAllIn: false,
    drillingPolicy: "Technician decides on site",
    idRequired: false,
    oldKeyDisabled: null,
    keysIncluded: 0,
    warranty: "None",
    quoteConfidence: "starts_at",
    redFlags: ["Refused to give total", "Starts at $39 pricing", "No ID required"],
    riskScore: 85,
    riskLevel: "High",
    transcriptEvidence: ["It starts at $39, the tech will tell you the rest."],
    transcript: "Keywize: How much will it cost to extract a broken key?\nSpeedy: It starts at $39.\nKeywize: Are there any hidden fees?\nSpeedy: Uh... well, it depends on the lock.",
    priceOrTermsChanged: false,
    voiceTrustSignals: mockVoiceTrustSignals.vendorA,
    voiceTrustScore: 35,
  },
  {
    id: "quote-b",
    missionId: "mission-001",
    vendorName: "Neighborhood Locksmith",
    phone: "(555) 837-1120",
    etaMinutes: 30,
    dispatchFee: 40,
    laborFee: 90,
    partsFee: 0,
    afterHoursFee: 0,
    taxesAndOther: 0,
    totalEstimate: 130,
    isTotalAllIn: true,
    drillingPolicy: "No-drill guarantee first",
    idRequired: true,
    oldKeyDisabled: null,
    keysIncluded: 0,
    warranty: "90 days",
    quoteConfidence: "firm_before_arrival",
    redFlags: [],
    riskScore: 10,
    riskLevel: "Low",
    transcriptEvidence: ["It's $130 total, including dispatch.", "We always try to pick it first without drilling."],
    transcript: "Keywize: What is the total cost?\nNeighborhood: It's $130 total, including dispatch.\nKeywize: Do you drill the lock?\nNeighborhood: We always try to pick it first without drilling.",
    priceOrTermsChanged: false,
    voiceTrustSignals: mockVoiceTrustSignals.vendorB,
    voiceTrustScore: 95,
  },
  {
    id: "quote-c",
    missionId: "mission-001",
    vendorName: "Premium Secure",
    phone: "(555) 991-4455",
    etaMinutes: 15,
    dispatchFee: 45,
    laborFee: 120,
    partsFee: 0,
    afterHoursFee: 0,
    taxesAndOther: 0,
    totalEstimate: 165,
    isTotalAllIn: true,
    drillingPolicy: "Will pick first",
    idRequired: true,
    oldKeyDisabled: null,
    keysIncluded: 0,
    warranty: "1 year",
    quoteConfidence: "firm_before_arrival",
    redFlags: ["Initial quote over budget ($150)"],
    riskScore: 25,
    riskLevel: "Medium",
    transcriptEvidence: ["Usually it's $165 for emergency extraction.", "Um, we can drop it to $145 if you book right now."],
    transcript: "Keywize: What is the total price?\nPremium: Usually it's $165 for emergency extraction.\nKeywize: Can you do $145? I have another quote for $130 but you are faster.\nPremium: Um, we can drop it to $145 if you book right now.",
    priceOrTermsChanged: false,
    voiceTrustSignals: mockVoiceTrustSignals.vendorC,
    voiceTrustScore: 65,
  },
];

export const mockMission: Mission = {
  id: "mission-001",
  jobSpec: mockJobSpec,
  quotes: mockQuotes,
  status: "intake",
  callLog: ["Intake complete", "Calling Speedy Lock & Key", "Calling Neighborhood Locksmith", "Calling Premium Secure"],
  recommendationId: null,
};
